global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'eye-api'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'eye-worker'
    static_configs:
      - targets: ['worker:2112'] # We will open this port on the worker
